### ISSUE TITLE
Composer plugin + require-dev

### ISSUE THREAD

**Issue by richardhj** [ErdmannFreunde/euf_nutshell_kit#8]
I want to propose two things:

1. Create a composer-plugin, so we don't need to define the scripts in the `compose.json` anymore. https://github.com/ErdmannFreunde/euf_nutshell_installer/pull/1
2. Move the dependency of the installer from `require` to `require-dev`. We don't need the installer on production systems.

## Tasks
* [x] Merge ErdmannFreunde/euf_nutshell_installer#1
* [x] Release euf_nutshell_installer v0.2.0
* [x] Add require-dev ErdmannFreunde/euf_nutshell_installer:^0.2 in this repository
* [x] Remove the require of ErdmannFreunde/euf_nutshell_installer:dev-master
* [x] Remove the two lines in the "scripts" section of the `composer.json`

## In case you want to test the changes

You can test the new version of the installer with this composer.json:

```json
{
    "name": "erdmannfreunde/euf_nutshell_kit",
    "description": "Start a new contao project based on the nutshell framework",
    "type": "project",
    "license": "GPL-3.0-or-later",
    "authors": [
        {
            "name": "Dennis Erdmann",
            "email": "dennis@erdmann-freunde.de"
        }
    ],
    "require": {
        "php": "^5.6|^7.0",
        "contao/manager-bundle": "4.4.*",
        "contao/calendar-bundle": "^4.4",
        "contao/comments-bundle": "^4.4",
        "contao/faq-bundle": "^4.4",
        "contao/listing-bundle": "^4.4",
        "contao/news-bundle": "^4.4",
        "contao/newsletter-bundle": "^4.4",
        "erdmannfreunde/euf_nutshell": "^0.4",
        "roave/security-advisories": "dev-master"
    },
    "require-dev": {
        "erdmannfreunde/euf_nutshell_installer": "dev-feature/composer-plugin"
    },
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:richardhj/euf_nutshell_installer.git"
        }
    ],
    "config": {
        "component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**Comment by denniserdmann** [comment]
I haven't had the time to look at composer plugins but your proposal sounds good to me. Do you have the rights to merge and release it by yourself?

**Comment by richardhj** [comment]
> Do you have the rights to merge and release it by yourself?

Hm no, but you can merge #9 :-)
